### ISSUE TITLE
Always triggers crash on quit

### ISSUE THREAD

**Issue by mbalandis** [Jack-Myth/UE4EditorCustomize#1]
When I quit UE4 and have the plugin enabled it always triggers Unreal Engine 4 Crash Reporter with 0 information about the crash. It doesn't seem to crash during use but still annoying that it does it.
version is 4.20.2

**Comment by Jack-Myth** [comment]
Thanks for your feedback,I will try to fix it.

**Comment by Jack-Myth** [comment]
The issue has been Fixed, I'm preparing to publish it.

**Comment by mbalandis** [comment]
Thanks a lot :)
Love the default theme, not even necessary to change! Very good job!

**Comment by Jack-Myth** [comment]
Thank you. I'm glad you like it.😁
